services:
  - type: web
    name: dasquiz-server-app
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    instanceCount: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BACKEND_URL
        value: https://api
    healthCheckPath: /healthz
