services:
  - type: web
    name: dasquiz-server-app
    env: node
    branch: main
    plan: free
    instanceCount: 1
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /healthz
